<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-U9J30NI6" failures="3" tests="4" name="BankingApp Test(failed)" time="29.12" errors="0" timestamp="2021-11-25T23:39:29 IST">
  <testcase classname="com.eBanking.testCases.LoginTest_TC_02_DDT" name="loginDDT" time="5.686">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.eBanking.testCases.LoginTest_TC_02_DDT.loginDDT(LoginTest_TC_02_DDT.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- loginDDT -->
  <testcase classname="com.eBanking.testCases.LoginTest_TC_02_DDT" name="loginDDT" time="5.205">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.eBanking.testCases.LoginTest_TC_02_DDT.loginDDT(LoginTest_TC_02_DDT.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- loginDDT -->
  <testcase classname="com.eBanking.testCases.LoginTest_TC_02_DDT" name="loginDDT" time="5.379">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.eBanking.testCases.LoginTest_TC_02_DDT.loginDDT(LoginTest_TC_02_DDT.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- loginDDT -->
  <testcase classname="com.eBanking.testCases.LoginTest_TC_001" name="loginTest" time="1.588"/>
</testsuite> <!-- BankingApp Test(failed) -->
